APPLICATION = tests_driver_spsgrf
BOARD = cgmfs

RIOTBASE ?= $(CURDIR)/../..

FEATURES_REQUIRED = periph_spi

USEMODULE += spsgrf
#USEMODULE += xtimer

QUIET ?= 1

include $(RIOTBASE)/Makefile.include
